-- M088 元数据-数据源管理
CREATE TABLE IF NOT EXISTS gov_meta_data_source (
    id                BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source_code       VARCHAR(64)  NOT NULL COMMENT '数据源编码',
    source_name       VARCHAR(128) NOT NULL COMMENT '名称',
    sort_order        INT          NOT NULL DEFAULT 0 COMMENT '排序',
    dept_name         VARCHAR(128) NULL COMMENT '部门名称',
    org_id            BIGINT       NULL COMMENT '所属组织ID',
    org_name          VARCHAR(128) NULL COMMENT '所属组织名称',
    category_id       BIGINT       NOT NULL COMMENT '所属分类',
    tag_category_id   BIGINT       NULL COMMENT '数据源标签(分类)',
    belong_system     VARCHAR(128) NULL COMMENT '所属系统',
    remarks           VARCHAR(512) NULL,
    adapter_type      VARCHAR(32)  NOT NULL DEFAULT 'MYSQL',
    realtime_flag     TINYINT      NOT NULL DEFAULT 0,
    read_only_flag    TINYINT      NOT NULL DEFAULT 1,
    db_host           VARCHAR(256) NULL,
    db_port           INT          NULL DEFAULT 3306,
    db_name           VARCHAR(128) NULL,
    db_schema         VARCHAR(128) NULL,
    username          VARCHAR(128) NULL,
    password_cipher   VARCHAR(512) NULL,
    connector_id      BIGINT       NULL COMMENT '关联 gov_om_connector',
    status            VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_by        VARCHAR(64)  NULL,
    created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_gov_meta_data_source_code (source_code),
    KEY idx_gov_meta_data_source_category (category_id),
    KEY idx_gov_meta_data_source_tag (tag_category_id),
    KEY idx_gov_meta_data_source_org (org_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据-数据源管理';
