-- D2：融合脚本

CREATE TABLE IF NOT EXISTS gov_fusion_script (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  script_code VARCHAR(64) NOT NULL,
  script_name VARCHAR(128) NOT NULL,
  script_type VARCHAR(32) NOT NULL DEFAULT 'SELECT' COMMENT 'SELECT/UPDATE',
  script_content MEDIUMTEXT NOT NULL,
  datasource_id BIGINT NULL COMMENT 'NULL=平台库',
  publish_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PUBLISHED',
  version_no INT NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  last_run_at DATETIME NULL,
  last_message VARCHAR(512) NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_fusion_script_code (script_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
