-- MS2 端到端演示 POC 表（能力等价最小闭环）

CREATE TABLE IF NOT EXISTS biz_data_asset (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  asset_code VARCHAR(64) NOT NULL,
  asset_name VARCHAR(128) NOT NULL,
  source_system VARCHAR(128) NULL,
  owner_org_id BIGINT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_asset_code (asset_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS biz_collect_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_name VARCHAR(128) NOT NULL,
  asset_id BIGINT NULL,
  schedule_cron VARCHAR(64) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'READY',
  last_run_at DATETIME NULL,
  last_message VARCHAR(512) NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS biz_catalog_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  catalog_code VARCHAR(64) NOT NULL,
  title VARCHAR(128) NOT NULL,
  description VARCHAR(512) NULL,
  publish_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_catalog_code (catalog_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS biz_data_demand (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  demand_title VARCHAR(128) NOT NULL,
  requester_org VARCHAR(128) NULL,
  target_catalog_id BIGINT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED',
  confirm_note VARCHAR(512) NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS biz_esb_flow (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  flow_code VARCHAR(64) NOT NULL,
  flow_name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'STOPPED',
  last_invoke_at DATETIME NULL,
  last_result VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_flow_code (flow_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS biz_kettle_job (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  job_code VARCHAR(64) NOT NULL,
  job_name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'IDLE',
  last_run_at DATETIME NULL,
  last_message VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_job_code (job_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO biz_esb_flow (flow_code, flow_name, status) VALUES
('MF_DEMO_001', '统一门户演示 MessageFlow', 'STOPPED')
ON DUPLICATE KEY UPDATE flow_name = VALUES(flow_name);

INSERT INTO biz_kettle_job (job_code, job_name, status) VALUES
('KTR_M215_DEMO', 'M215 ETL 演示作业', 'IDLE')
ON DUPLICATE KEY UPDATE job_name = VALUES(job_name);

INSERT INTO biz_catalog_item (catalog_code, title, description, publish_status, created_by) VALUES
('CAT_DEMO_001', '企业基础信息目录', '共享门户演示目录项', 'PUBLISHED', 'sys_admin')
ON DUPLICATE KEY UPDATE title = VALUES(title);
