-- GB/T 21063.4-2007 附录A 主题分类：标准标签库 + 资产挂标
-- 一级 21，二级 133

ALTER TABLE ing_asset_tag
  ADD COLUMN parent_id BIGINT NULL COMMENT '父标签ID' AFTER id,
  ADD COLUMN level TINYINT NULL COMMENT '1一级 2二级' AFTER parent_id,
  ADD COLUMN tag_source VARCHAR(16) NOT NULL DEFAULT 'CUSTOM' COMMENT 'STANDARD/CUSTOM' AFTER level,
  ADD COLUMN std_code VARCHAR(16) NULL COMMENT '国标类目编码' AFTER tag_source;

ALTER TABLE ing_asset_tag
  ADD UNIQUE KEY uk_ing_asset_tag_std_code (std_code),
  ADD KEY idx_ing_asset_tag_parent (parent_id),
  ADD KEY idx_ing_asset_tag_source (tag_source);

UPDATE ing_asset_tag SET tag_source = 'CUSTOM' WHERE tag_source IS NULL OR tag_source = '';

CREATE TABLE IF NOT EXISTS ing_asset_tag_binding (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tag_id BIGINT NOT NULL,
  asset_type VARCHAR(16) NOT NULL COMMENT 'TABLE/COLUMN',
  asset_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tag_asset (tag_id, asset_type, asset_id),
  KEY idx_asset (asset_type, asset_id),
  KEY idx_tag (tag_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产标签绑定';

-- 标准一级类目
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZA', '综合政务', '', '关于政治方面的事务和国家的管理工作', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZA');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZB', '经济管理', '', '关于经济的管理、规划、发展概况', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZB');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZC', '国土资源、能源', '', '土地、水、海洋、石油、天然气、矿藏、电力资源的管理、规划和发展', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZC');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZD', '工业、交通', '', '工业、企业、交通运输、邮政及相关领域', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZD');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZE', '信息产业', '', '与信息产业内以及相关的行业领域', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZE');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZF', '城乡建设、环境保护', '', '关于城乡建设的规划和发展情况，以及环境的监测、环境保护及其相关领域', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZF');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZG', '农业、水利', '', '关于农业、畜牧业、林业、副业、渔业、水利的规章制度、法律法规、发展规划等', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZG');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZH', '财政', '', '财政、会计、金融、保险、税务、审计等', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZH');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZJ', '商业、贸易', '', '商业指以货币为媒介进行交换从而实现商品流通的经济活动；贸易指买卖的通称', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZJ');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZK', '旅游、服务业', '', '外出游览或为他人提供服侍、帮助的行业', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZK');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZL', '气象、水文、测绘、地震', '', '大气现象，自然界中水的变化、运动等的各种现象，测量和地图制图，地壳的天然震动', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZL');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZM', '对外事务', '', '一个国家在国际关系方面的活动的行政事务、总务', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZM');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZN', '政法、监察', '', '政治和法律，监督和考察', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZN');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZP', '科技、教育', '', '科学技术；培养人才、传播知识的工作', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZP');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZQ', '文化、卫生、体育', '', '文化、卫生、体育相关事务', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZQ');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZR', '军事、国防', '', '与军队或战争有关的事情；保卫国家主权、领土、领海和领空的完整和安全', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZR');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZS', '劳动、人事', '', '劳动就业和社会保障；工作人员的录用、培养、调配、奖罚等工作', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZS');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZT', '民政、社区', '', '政府处理的有关人民的行政事务；同一地区人所组成的整体', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZT');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZU', '文秘、行政', '', '处理文书文件类秘书；企事业、各种社会团体等的内部管理', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZU');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZV', '综合党团', '', '宗教、民族、侨民、党派团体、特别行政区的综合事务', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZV');
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) VALUES ('STD_ZW', '综合类', '', '综合类', 0, 'ACTIVE', NULL, 1, 'STANDARD', 'ZW');

-- 标准二级类目（parent_id 按 std_code 关联一级）
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAA00', '政务综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAA00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAB00', '方针政策', '', '政府制订的、宏观的、指导各个领域发展的方针政策', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAB00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAC00', '中共党务', '', '关于中国共产党的规章制度、组织机构建设和发展，以及工作职责等相关信息', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAC00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAD00', '政府工作', '', '关于政府的规章制度、组织机构建设和发展，以及工作职责等相关信息', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAD00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAE00', '人大', '', '关于人民代表大会的规章制度、组织机构建设和发展，以及工作职责的相关信息', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAE00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAF00', '政协', '', '政治协商会议的规章制度、组织机构建设和发展，以及工作职责等相关信息', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAF00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAG00', '法院', '', '法院系统的规章制度、组织机构建设和发展，以及工作职责等相关信息', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAG00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAH00', '检察院', '', '检察院系统的规章制度、组织机构建设和发展，以及工作职责等相关信息', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAH00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAJ00', '机构编制', '', '关于机构编制的管理、机构体系的当前概况和远景规划', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAJ00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAK00', '领导人', '', '关于领导人的简历、工作岗位、工作活动、作品等相关信息', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAK00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAL00', '会议、会务', '', '会议产生的报告等相关信息，以及会议组织、管理的相关信息', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAL00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZAM00', '重大事件', '', '有深远影响的事件的相关信息', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZAM00' FROM ing_asset_tag t WHERE t.std_code = 'ZA' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZBA00', '经济管理综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZBA00' FROM ing_asset_tag t WHERE t.std_code = 'ZB' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZBB00', '经济发展计划', '', '关于经济的宏观的发展规划', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZBB00' FROM ing_asset_tag t WHERE t.std_code = 'ZB' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZBC00', '经济管理', '', '关于经济的宏观管理现状', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZBC00' FROM ing_asset_tag t WHERE t.std_code = 'ZB' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZBD00', '经济体制改革', '', '关于经济体制改革的管理和规划、发展情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZBD00' FROM ing_asset_tag t WHERE t.std_code = 'ZB' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZBE00', '经贸管理', '', '关于经济贸易的宏观管理和发展调查报告、统计资料', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZBE00' FROM ing_asset_tag t WHERE t.std_code = 'ZB' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZBF00', '统计', '', '关于统计工作的管理和发展情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZBF00' FROM ing_asset_tag t WHERE t.std_code = 'ZB' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZBG00', '物价', '', '关于物价的管理和调查报告、统计资料，以及物价体系规划', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZBG00' FROM ing_asset_tag t WHERE t.std_code = 'ZB' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZBH00', '工商', '', '关于市场监督管理和维护公平竞争的市场秩序', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZBH00' FROM ing_asset_tag t WHERE t.std_code = 'ZB' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZCA00', '国土资源与能源综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZCA00' FROM ing_asset_tag t WHERE t.std_code = 'ZC' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZCB00', '土地', '', '关于土地资源的管理、规划和开发利用情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZCB00' FROM ing_asset_tag t WHERE t.std_code = 'ZC' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZCC00', '矿藏', '', '关于矿产资源的管理、规划和开发利用情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZCC00' FROM ing_asset_tag t WHERE t.std_code = 'ZC' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZCD00', '水资源', '', '关于水资源的管理、规划和开发利用情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZCD00' FROM ing_asset_tag t WHERE t.std_code = 'ZC' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZCE00', '海洋', '', '关于海洋资源的管理、规划和开发利用情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZCE00' FROM ing_asset_tag t WHERE t.std_code = 'ZC' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZCF00', '煤炭', '', '关于煤炭资源的管理、规划和开发利用情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZCF00' FROM ing_asset_tag t WHERE t.std_code = 'ZC' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZCG00', '石油', '', '关于石油、天然气行业生产、经营的规章制度、法律法规、规划和管理', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZCG00' FROM ing_asset_tag t WHERE t.std_code = 'ZC' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZCH00', '燃料、燃气', '', '关于燃料、燃气行业生产、经营的规章制度、法律法规、规划和管理', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZCH00' FROM ing_asset_tag t WHERE t.std_code = 'ZC' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZCJ00', '电力', '', '关于电力生产和市场经营的规章制度、法律法规、管理机构，以及设施建设和技术发展', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZCJ00' FROM ing_asset_tag t WHERE t.std_code = 'ZC' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZDA00', '工交综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZDA00' FROM ing_asset_tag t WHERE t.std_code = 'ZD' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZDB00', '工业', '', '关于工业的规章制度、法律法规、管理机构、体系结构规划和发展', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZDB00' FROM ing_asset_tag t WHERE t.std_code = 'ZD' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZDC00', '企业', '', '关于企业创建、经营的规章制度、法律法规、管理机构和政府对企业提供的相关服务', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZDC00' FROM ing_asset_tag t WHERE t.std_code = 'ZD' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZDD00', '交通运输', '', '关于交通运输业的规章制度、法律法规、管理机构、功能服务和设施建设的规划和发展情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZDD00' FROM ing_asset_tag t WHERE t.std_code = 'ZD' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZEA00', '信息产业综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZEA00' FROM ing_asset_tag t WHERE t.std_code = 'ZE' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZEB00', '通信', '', '与通信相关的规章制度、法律法规、设施建设、功能服务以及组织机构等', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZEB00' FROM ing_asset_tag t WHERE t.std_code = 'ZE' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZEC00', '计算机', '', '与计算机相关的研发、生产、销售相关的规章制度、法律法规、技术和标准，以及该行业的市场行情等概况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZEC00' FROM ing_asset_tag t WHERE t.std_code = 'ZE' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZED00', '软件', '', '与软件业相关的规章制度、法律法规、技术标准和发展概况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZED00' FROM ing_asset_tag t WHERE t.std_code = 'ZE' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZEE00', '网络', '', '关于网络的规章制度、法律法规、设施建设规划和发展情况，以及网络的功能服务', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZEE00' FROM ing_asset_tag t WHERE t.std_code = 'ZE' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZEF00', '信息技术、信息系统', '', '关于信息系统建设的规划和发展情况，信息系统功能服务的开发利用，以及相关的规章制度、法律法规，信息技术的研发', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZEF00' FROM ing_asset_tag t WHERE t.std_code = 'ZE' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZEG00', '邮政', '', '关于邮政业的规章制度、法律法规、设施建设的规划和发展情况，功能服务的开发利用', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZEG00' FROM ing_asset_tag t WHERE t.std_code = 'ZE' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZFA00', '城乡建设与环境保护综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZFA00' FROM ing_asset_tag t WHERE t.std_code = 'ZF' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZFB00', '城乡规划', '', '关于城乡规划方面的规章制度、法律法规、规划报告', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZFB00' FROM ing_asset_tag t WHERE t.std_code = 'ZF' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZFC00', '城乡建设', '', '城乡的建设发展情况，包括公共设施建设和园林建设', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZFC00' FROM ing_asset_tag t WHERE t.std_code = 'ZF' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZFD00', '市政工程', '', '市政建设的发展情况，包括道路、桥梁、隧道等的建设，以及供水、供气方面的建设情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZFD00' FROM ing_asset_tag t WHERE t.std_code = 'ZF' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZFE00', '房地产', '', '关于房地产行业的规章制度、法律法规，以及房地产市场和开发商的调查报告、统计资料等', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZFE00' FROM ing_asset_tag t WHERE t.std_code = 'ZF' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZFF00', '环境保护、治理', '', '包括环境保护方面的科学知识、规章制度、法律法规、当前环境概况，以及相关环保经济领域的发展情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZFF00' FROM ing_asset_tag t WHERE t.std_code = 'ZF' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZFG00', '环境污染、监测', '', '关于环境监测的统计报告和技术标准', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZFG00' FROM ing_asset_tag t WHERE t.std_code = 'ZF' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZGA00', '农业水利综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZGA00' FROM ing_asset_tag t WHERE t.std_code = 'ZG' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZGB00', '农业', '', '关于农业的规章制度、法律法规、农产品市场、农业组织、农业科技、农业基础设施建设', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZGB00' FROM ing_asset_tag t WHERE t.std_code = 'ZG' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZGC00', '林业', '', '关于林业的规划、建设情况、规章制度、法律法规、科学技术、组织机构和相关领域经济情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZGC00' FROM ing_asset_tag t WHERE t.std_code = 'ZG' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZGD00', '畜牧业', '', '关于畜牧业的规章制度、法律法规、设施建设、科学技术和相关领域经济发展情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZGD00' FROM ing_asset_tag t WHERE t.std_code = 'ZG' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZGE00', '副业', '', '关于副业发展的规章制度、法律法规、设施建设、科学技术和相关领域的经济发展情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZGE00' FROM ing_asset_tag t WHERE t.std_code = 'ZG' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZGF00', '渔业', '', '关于渔业发展的规章制度、法律法规、科学技术、设施建设和相关领域的经济发展情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZGF00' FROM ing_asset_tag t WHERE t.std_code = 'ZG' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZGG00', '水利', '', '关于水利建设的规划和发展、规章制度、法律法规、科学技术和组织机构', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZGG00' FROM ing_asset_tag t WHERE t.std_code = 'ZG' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZHA00', '财政综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZHA00' FROM ing_asset_tag t WHERE t.std_code = 'ZH' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZHB00', '财政', '', '关于财政的规章制度、法律法规、业务管理、统计资料', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZHB00' FROM ing_asset_tag t WHERE t.std_code = 'ZH' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZHC00', '税务', '', '关于税务的规章制度、法律法规、理论知识、税务体系建设', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZHC00' FROM ing_asset_tag t WHERE t.std_code = 'ZH' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZHD00', '金融', '', '关于金融的规章制度、法律法规、理论知识、组织机构、金融经济统计资料', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZHD00' FROM ing_asset_tag t WHERE t.std_code = 'ZH' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZHE00', '保险', '', '关于保险的规章制度、法律法规、理论知识、组织机构、保险经济统计资料', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZHE00' FROM ing_asset_tag t WHERE t.std_code = 'ZH' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZHF00', '审计', '', '关于审计的规章制度、法律法规、理论知识、组织机构', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZHF00' FROM ing_asset_tag t WHERE t.std_code = 'ZH' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZHG00', '会计', '', '关于会计的规章制度、法律法规、组织机构、理论知识和行业发展情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZHG00' FROM ing_asset_tag t WHERE t.std_code = 'ZH' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZJA00', '商贸综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZJA00' FROM ing_asset_tag t WHERE t.std_code = 'ZJ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZJB00', '国内贸易', '', '在国内进行的买卖', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZJB00' FROM ing_asset_tag t WHERE t.std_code = 'ZJ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZJC00', '对外贸易', '', '在国际间进行的买卖', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZJC00' FROM ing_asset_tag t WHERE t.std_code = 'ZJ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZJD00', '物流、仓储', '', '物资流动、仓库储备', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZJD00' FROM ing_asset_tag t WHERE t.std_code = 'ZJ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZJE00', '海关', '', '交纳关税和货船报关结关的地方', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZJE00' FROM ing_asset_tag t WHERE t.std_code = 'ZJ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZJF00', '检验、检疫', '', '检查并验证或为防止传染病蔓延，对可能成为传染源的人员、交通工具、物资等采取隔离观察、消毒等措施', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZJF00' FROM ing_asset_tag t WHERE t.std_code = 'ZJ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZKA00', '旅游、服务业综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZKA00' FROM ing_asset_tag t WHERE t.std_code = 'ZK' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZKB00', '旅游', '', '外出游览、观光', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZKB00' FROM ing_asset_tag t WHERE t.std_code = 'ZK' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZKC00', '服务业', '', '为他人提供服侍这一职业', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZKC00' FROM ing_asset_tag t WHERE t.std_code = 'ZK' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZLA00', '气象水文综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZLA00' FROM ing_asset_tag t WHERE t.std_code = 'ZL' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZLB00', '气象', '', '大气现象', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZLB00' FROM ing_asset_tag t WHERE t.std_code = 'ZL' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZLC00', '水文', '', '自然界中水的变化、运动等的各种现象', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZLC00' FROM ing_asset_tag t WHERE t.std_code = 'ZL' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZLD00', '测绘', '', '测量和地图制图', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZLD00' FROM ing_asset_tag t WHERE t.std_code = 'ZL' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZLE00', '地震', '', '地壳的天然震动', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZLE00' FROM ing_asset_tag t WHERE t.std_code = 'ZL' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZMA00', '对外事务综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZMA00' FROM ing_asset_tag t WHERE t.std_code = 'ZM' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZMB00', '外交', '', '一个国家在国际关系方面的活动', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZMB00' FROM ing_asset_tag t WHERE t.std_code = 'ZM' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZMC00', '外事活动', '', '外交事务、涉外事务方面的活动', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZMC00' FROM ing_asset_tag t WHERE t.std_code = 'ZM' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZMD00', '国际关系', '', '一个国家与其他各国及其公民之间的关系', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZMD00' FROM ing_asset_tag t WHERE t.std_code = 'ZM' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZME00', '国际组织', '', '各国及其公民之间按照一定的目的、任务和形式组成的国际性团体机构', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZME00' FROM ing_asset_tag t WHERE t.std_code = 'ZM' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZMF00', '国际会议', '', '各国之间共同议事，并遵循一定的议程，所举行的一种集会', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZMF00' FROM ing_asset_tag t WHERE t.std_code = 'ZM' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZNA00', '政法综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZNA00' FROM ing_asset_tag t WHERE t.std_code = 'ZN' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZNB00', '公安', '', '社会的公共治安', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZNB00' FROM ing_asset_tag t WHERE t.std_code = 'ZN' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZNC00', '国家安全', '', '国家的独立、主权、统一和领土完整不受侵犯，国家的政权、政治制度、经济制度和社会秩序不被破坏，国家的荣誉和利益不遭损害', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZNC00' FROM ing_asset_tag t WHERE t.std_code = 'ZN' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZND00', '监察', '', '监督考察', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZND00' FROM ing_asset_tag t WHERE t.std_code = 'ZN' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZNE00', '司法', '', '行使法律权力', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZNE00' FROM ing_asset_tag t WHERE t.std_code = 'ZN' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZPA00', '科教综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZPA00' FROM ing_asset_tag t WHERE t.std_code = 'ZP' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZPB00', '科技管理', '', '对科学技术研究工作进行管理', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZPB00' FROM ing_asset_tag t WHERE t.std_code = 'ZP' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZPC00', '科研工作', '', '科学研究工作', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZPC00' FROM ing_asset_tag t WHERE t.std_code = 'ZP' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZPD00', '知识产权', '', '公民、法人或其他组织对其在科学技术和文学艺术等领域内主要基于脑力劳动创造完成的智力成果所依法享有的专有权利', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZPD00' FROM ing_asset_tag t WHERE t.std_code = 'ZP' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZPE00', '技术监督', '', '对劳动生产方面的经验、知识和技巧有权进行检查管理', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZPE00' FROM ing_asset_tag t WHERE t.std_code = 'ZP' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZPF00', '教育', '', '培养人才、传播知识的工作，主要指学校教育', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZPF00' FROM ing_asset_tag t WHERE t.std_code = 'ZP' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZPG00', '院校管理', '', '对各类学院、学校进行管理', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZPG00' FROM ing_asset_tag t WHERE t.std_code = 'ZP' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZQA00', '文体综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZQA00' FROM ing_asset_tag t WHERE t.std_code = 'ZQ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZQB00', '语言文字', '', '语言是用以表达情意的声音；文字是记录语言的符号', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZQB00' FROM ing_asset_tag t WHERE t.std_code = 'ZQ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZQC00', '文学艺术', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZQC00' FROM ing_asset_tag t WHERE t.std_code = 'ZQ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZQD00', '文物、考古', '', '文物是指历代遗留下来的具有历史、艺术价值的东西；考古是根据古代遗迹、遗物和文献研究古代事物', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZQD00' FROM ing_asset_tag t WHERE t.std_code = 'ZQ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZQE00', '新闻出版', '', '图书、期刊、音像制品、电子出版物、网络出版物、投影片等出版业务', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZQE00' FROM ing_asset_tag t WHERE t.std_code = 'ZQ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZQF00', '广播、电影、电视', '', '广播、电影、电视相关传播与内容', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZQF00' FROM ing_asset_tag t WHERE t.std_code = 'ZQ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZQG00', '医药卫生管理', '', '对药品生产、流通、医疗器械企业进行管理', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZQG00' FROM ing_asset_tag t WHERE t.std_code = 'ZQ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZQH00', '医疗保健', '', '治疗人体疾病，保护和增进人体健康', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZQH00' FROM ing_asset_tag t WHERE t.std_code = 'ZQ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZQJ00', '计划生育', '', '通过有效的控制生育的方法来执行制订子女人数和生育间隔时间', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZQJ00' FROM ing_asset_tag t WHERE t.std_code = 'ZQ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZQK00', '体育', '', '娱乐消遣活动或需体力、智慧与技巧的比赛或竞技', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZQK00' FROM ing_asset_tag t WHERE t.std_code = 'ZQ' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZRA00', '军事国防综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZRA00' FROM ing_asset_tag t WHERE t.std_code = 'ZR' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZRB00', '国防建设', '', '为保卫国家主权、领土、领海和领空完整和安全，防御外来武装侵略和颠覆而进行的建设活动', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZRB00' FROM ing_asset_tag t WHERE t.std_code = 'ZR' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZRC00', '军事工作', '', '与军队或战争有关事宜的工作', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZRC00' FROM ing_asset_tag t WHERE t.std_code = 'ZR' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZRD00', '军队政治工作', '', '保证革命政党对军队的领导，使军队成为革命政党实现革命目的的工具', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZRD00' FROM ing_asset_tag t WHERE t.std_code = 'ZR' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZRE00', '军事后勤工作', '', '与军队或战争有关的后方对前方的一切供应工作', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZRE00' FROM ing_asset_tag t WHERE t.std_code = 'ZR' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZRF00', '军事装备工作', '', '与军队或战争有关的配备工作', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZRF00' FROM ing_asset_tag t WHERE t.std_code = 'ZR' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZRG00', '军事技术', '', '与军队或战争有关的经验、知识和技巧', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZRG00' FROM ing_asset_tag t WHERE t.std_code = 'ZR' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZRH00', '武警', '', '武装警察', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZRH00' FROM ing_asset_tag t WHERE t.std_code = 'ZR' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZSA00', '劳动人事综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZSA00' FROM ing_asset_tag t WHERE t.std_code = 'ZS' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZSB00', '人事工作', '', '关于工作人员的录用、培养、调配、奖罚等工作', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZSB00' FROM ing_asset_tag t WHERE t.std_code = 'ZS' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZSC00', '劳动就业', '', '就业的基本政策、措施、方针、标准、劳动关系调整的基本规则', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZSC00' FROM ing_asset_tag t WHERE t.std_code = 'ZS' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZSD00', '社会保障', '', '主要指社会保险', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZSD00' FROM ing_asset_tag t WHERE t.std_code = 'ZS' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZSE00', '工资职称', '', '付给劳动者劳动报酬和科学技术人员等级', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZSE00' FROM ing_asset_tag t WHERE t.std_code = 'ZS' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZSF00', '福利待遇', '', '生活上的利益和享有的权利及物质报酬', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZSF00' FROM ing_asset_tag t WHERE t.std_code = 'ZS' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZTA00', '民政综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZTA00' FROM ing_asset_tag t WHERE t.std_code = 'ZT' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZTB00', '民政', '', '政府处理的有关人民的行政事务', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZTB00' FROM ing_asset_tag t WHERE t.std_code = 'ZT' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZTC00', '社区', '', '同一地区人所组成的整体', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZTC00' FROM ing_asset_tag t WHERE t.std_code = 'ZT' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZUA00', '文秘行政综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZUA00' FROM ing_asset_tag t WHERE t.std_code = 'ZU' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZUB00', '文秘工作', '', '处理文书、文件类的工作', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZUB00' FROM ing_asset_tag t WHERE t.std_code = 'ZU' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZUC00', '文种', '', '能概括表明每一种公文性质、用途的统一规范称谓', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZUC00' FROM ing_asset_tag t WHERE t.std_code = 'ZU' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZUD00', '机要、保密', '', '重要而机密、保守秘密', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZUD00' FROM ing_asset_tag t WHERE t.std_code = 'ZU' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZUE00', '档案', '', '国家机构、社会组织以及个人从事政治、军事、经济、科学、技术、文化、宗教等活动直接形成的对国家和社会有保存价值的各种文字、图表、声像等不同形式的历史记录', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZUE00' FROM ing_asset_tag t WHERE t.std_code = 'ZU' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZUF00', '信访工作', '', '接受和处理群众通过信函或面谈方式反映问题的工作', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZUF00' FROM ing_asset_tag t WHERE t.std_code = 'ZU' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZUG00', '行政事务', '', '政府机关、企事业、各种社会团体等的内部执行管理的杂务', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZUG00' FROM ing_asset_tag t WHERE t.std_code = 'ZU' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZVA00', '党团综合类', '', '', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZVA00' FROM ing_asset_tag t WHERE t.std_code = 'ZV' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZVB00', '党派团体', '', '关于各党派团体的概况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZVB00' FROM ing_asset_tag t WHERE t.std_code = 'ZV' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZVC00', '民族事务', '', '关于少数民族事业的发展概况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZVC00' FROM ing_asset_tag t WHERE t.std_code = 'ZV' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZVD00', '宗教', '', '关于宗教事务的管理和发展情况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZVD00' FROM ing_asset_tag t WHERE t.std_code = 'ZV' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZVE00', '侨务工作', '', '关于侨务工作的管理和发展概况，以及侨民概况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZVE00' FROM ing_asset_tag t WHERE t.std_code = 'ZV' AND t.level = 1 LIMIT 1;
INSERT INTO ing_asset_tag (tag_code, tag_name, rule_expr, tag_desc, hit_count, status, parent_id, level, tag_source, std_code) SELECT 'STD_ZVF00', '港澳台工作', '', '关于香港、澳门、台湾的政策法规、政治、经济、科技交流往来等概况', 0, 'ACTIVE', t.id, 2, 'STANDARD', 'ZVF00' FROM ing_asset_tag t WHERE t.std_code = 'ZV' AND t.level = 1 LIMIT 1;
