/** 业务状态码 / 枚举码 → 中文展示（API 仍传英文码，仅 UI 转换） */

const STATUS_ZH: Record<string, string> = {
  // 通用启用
  ACTIVE: '启用',
  INACTIVE: '停用',
  ENABLED: '启用',
  DISABLED: '已停用',
  // 草稿/发布
  DRAFT: '草稿',
  TO_REGISTER: '待发布',
  PUBLISHED: '已发布',
  PUBLISH: '发布',
  DEV: '开发',
  PROD: '生产',
  CREATE: '创建',
  ALTER: '变更',
  UPDATE: '更新',
  OFFLINE: '已下线',
  ARCHIVED: '已归档',
  ARCHIVE: '归档',
  PENDING_ARCHIVE: '待审核',
  PENDING_REVIEW: '待审核',
  CAT_CREATE: '分类新增',
  CAT_UPDATE: '分类编辑',
  CAT_DELETE: '分类删除',
  METADATA: '元数据',
  // 监控/预检
  OK: '正常',
  WARN: '预警',
  CRITICAL: '严重',
  BLOCKED: '阻断',
  // 审批/订阅
  PENDING_PLATFORM: '待平台审核',
  PENDING_PROVIDER: '待提供方审核',
  PENDING: '待审核',
  APPROVED: '已审核',
  REJECTED: '驳回待提交',
  CANCELLED: '已撤销',
  WITHDRAWN: '已撤回',
  WITHDRAW_PENDING: '撤销待提交',
  RETURNED: '已退回',
  PROVIDER_RETURNED: '提供方退回待裁决',
  SUBSCRIBED: '已订阅',
  DISTRIBUTED: '已分发',
  DATA_UPDATE: '数据变更',
  DATA_INSERT: '数据新增',
  META_UPDATE: '元数据变更',
  SCHEMA_CHANGE: '结构变更',
  REPUBLISH: '重新发布',
  INTERNAL_SYSTEM: '内部系统',
  SUPERIOR: '上级单位',
  CITY_BIGDATA: '市大数据中心',
  NATIONAL_LOCAL_BIGDATA: '国家/地方大数据中心',
  THIRD_PARTY: '第三方业务应用',
  CHANGE: '变更触发',
  APPROVE: '审批触发',
  LEDGER: '已记台账',
  ACKED: '已确认',
  // 运行/任务
  IDLE: '空闲',
  READY: '已配置',
  CONFIGURED: '已配置',
  RUNNING: '运行中',
  SUCCESS: '成功',
  DESTROYED: '已销毁',
  ALL_SUCCESS: '全部成功',
  PARTIAL: '部分成功',
  NONE: '未执行', // 执行/运行默认；压缩/加密/计算结果须走 statusLabel(v, domain)
  FAILED: '失败',
  ONLINE: '在线',
  BUSY: '繁忙',
  DRAIN: '排空中',
  QUEUED: '排队中',
  WAITING: '等待中',
  STARTED: '已启动',
  OFFLINE: '已下线',
  DISPLAY: '显示',
  COMPONENT: '组件',
  MAP: '地图',
  DATASOURCE: '数据源',
  DESIGN: '设计',
  SELF_SERVICE: '自助',
  DATA_OPS: '区设计',
  ANALYSIS: '分析模型',
  LEDGER: '台账处理',
  EMAIL: '邮件',
  SMS: '短信',
  ERROR: '错误',
  FATAL: '致命',
  FRONTEND: '前端',
  BACKEND: '后端',
  JOB: '任务',
  GATEWAY: '网关',
  COMPLETED: '已办结',
  FINISHED: '已完成',
  STOPPED: '已停止',
  CLOSED: '已关闭',
  OPEN: '开放',
  SKIPPED: '已跳过',
  NOT_RUN: '未运行',
  NOT_GENERATED: '未生成',
  // 供需
  SUBMITTED: '待数据主管部门审核',
  ANALYZING: '预审中',
  PRE_AUDITING: '预审中',
  PRE_AUDIT: '预审',
  AUDIT: '审核',
  CONFIRMED: '已确认',
  CATALOG_MOUNTED: '已挂载',
  DISPATCHED: '待确认',
  SUPERVISING: '督办中',
  CORRECTION: '异议回流',
  FULFILLING: '履约中',
  MATCHED: '已匹配',
  UNMATCHED: '未匹配',
  CONFIRM: '审核',
  ANALYZE: '预审',
  MANAGE: '填报',
  SUPPLY: '供给',
  // 采集/解析/索引
  PARSED: '已解析',
  COMMITTED: '已入库',
  PREVIEWED: '已预览',
  UPLOADED: '已上传',
  REGISTERED: '已登记',
  INDEXED: '已索引',
  RAW: '原始',
  EXTRACTED: '已提取特征',
  UNDERSTOOD: '已内容理解',
  CLEANED: '已清洗',
  PROBLEM: '问题数据',
  ABANDONED: '已放弃',
  CLEANED_IN: '清洗后入库',
  OTHER: '其他处理',
  OPEN: '待确认',
  DEDUP: '去重',
  VALIDATE: '校验',
  TRANSFORM: '转换',
  INFO: '信息',
  CRITICAL: '严重',
  TAGGED: '已标注',
  LINKED: '已关联',
  EXTRACT: '关联提取',
  ANALYZE: '关联分析',
  BACKFILL: '关联回填',
  SUCCESS: '成功',
  SIMILARITY: '相似度',
  KEYWORD: '关键词',
  POSITIVE: '正向',
  NEGATIVE: '负向',
  NEUTRAL: '中性',
  // 评估
  EVALUATING: '评估中',
  SCORED: '已打分',
  // 其它常见
  NORMAL: '正常',
  ABNORMAL: '异常',
  UNKNOWN: '未知',
  NEW: '新建',
  CHANGED: '已变更',
  UNCHANGED: '未变更',
  SYNCED: '已同步',
  // 元数据版本来源
  SCHEDULED_COLLECT: '定时采集',
  MAINTAIN: '维护',
  ROLLBACK: '回滚',
  MANUAL: '手工',
  UNREAD: '未读',
  READ: '已读',
  ACKED: '已确认',
  LOCKED: '已锁定',
  EXPIRED: '已过期',
  UNTESTED: '未测试',
  ONLINE: '在线',
  // 访问控制授权级别
  VIEW: '查看',
  EDIT: '编辑',
  ADMIN: '管理',
  ACCESS: '访问',
  READ: '只读',
  WRITE: '读写',
  USER: '用户',
  ROLE: '角色',
  ORG: '机构',
  PROJECT: '项目',
  // 标准对标
  MAPPED: '已对标',
  UNMAPPED: '未对标',
  // 元数据条目类型
  SOURCE: '数据源',
  CONNECTOR: '连接器',
  TABLE: '数据表',
  COLUMN: '字段',
  CATALOG: '编目',
  MODEL: '元模型',
  LINEAGE: '血缘',
  COLUMN_LINEAGE: '字段血缘',
  VERSION: '版本',
  METRIC: '指标',
  SERVICE: '服务',
  FILE: '文件',
  API: '接口',
  DATA: '数据',
  // 供需对接：期望共享数据提供方式（含历史细分码）
  QUERY_API: '接口',
  VERIFY_API: '接口',
  TABLE_EXCHANGE: '库表',
  FILE_EXCHANGE: '文件',
  // 安全分级
  PUBLIC: '公开',
  PRIVATE: '未公开',
  INTERNAL: '内部',
  SENSITIVE: '敏感',
  SECRET: '核心',
  CORE: '核心',
  REVOKED: '已撤销',
  ROLE_GRANT: '角色授权',
  DATA_ACCESS: '数据访问授权',
  DUAL: '双重授权',
  SINGLE: '单重授权',
  MASKED_READ: '脱敏只读',
  ALERT: '告警通知',
  ESCALATE: '升级通知',
  EQUIVALENT: '等价',
  ALIAS: '别名',
  REFINES: '细化',
  LEGAL_BASE: '法人基础数据',
  LEGAL_BIZ: '法人业务主题',
  POP_BASE: '人口基础数据',
  POP_BIZ: '人口业务主题',
  IDENTITY: '身份证件信息',
  CONTACT: '联系信息',
  HIGH_SENSITIVE_BOUNDARY: '高敏独立边界',
  CONSUME_CORE: '消费核心权威',
  CLASSIFY_DUAL_AUTH: '分级分类与双重授权',
  FROM_CORE: '来源核心区',
  DEPT_HIGH_SENS: '部门高敏应用',
  AES256: 'AES-256',
  SM4: '国密SM4',
  NO_ENCRYPTION: '不加密',
  // 采集范围 / 符合度 / 分层
  FULL: '整库',
  PASS: '通过',
  FAIL: '不通过',
  SKIP: '未校验',
  ODS: 'ODS',
  DWD: 'DWD',
  DWS: 'DWS',
  ADS: 'ADS',
  EXTERNAL: '外部',
  // 关系类型
  FK: '外键',
  IMPACT: '影响',
  ASSOC: '关联',
  ROOT: '分析起点',
  // 健康
  UP: '可用',
  DOWN: '不可用',
  // 治理 ETL 节点类型
  INPUT: '输入',
  OUTPUT: '输出',
  FILTER: '过滤',
  FIELD_PROCESS: '字段处理',
  DEDUPLICATE: '去重',
  MASK: '脱敏',
  SPLIT: '表拆分',
  SORT: '排序',
  JOIN: '关联',
  UNION: '合并',
  AGGREGATE: '聚合',
  PIVOT: '行转列',
  UNPIVOT: '列转行',
  SET_VARIABLE: '参数设置',
  VALUE_MAPPER: '值映射',
  CONSTANT: '增加常量',
  FORMULA: '计算公式',
  STRING_CUT: '字符串裁剪',
  REPLACE_STRING: '字符串替换',
  NULL_IF: '空值处理',
  IF_NULL: '空值填充',
  TYPE_CONVERT: '类型转换',
  SELECT_FIELDS: '字段选择',
  SWITCH_CASE: '流拆分',
  VALIDATOR: '数据校验',
  SCRIPT: '脚本',
  TEXT_INPUT: '文本输入',
  TEXT_OUTPUT: '文本输出',
  EXCEL_INPUT: 'Excel输入',
  INSERT_UPDATE: '插入更新',
  DB_LOOKUP: '库表查找',
  HTTP: 'HTTP接口',
  // D05 模块实现状态
  IMPLEMENTED: '已实装',
  POC: 'PoC演示',
  STUB: '占位',
  MISSING: '待开发',
  // 共享方式 / 路径
  DB_SYNC: '库表同步',
  FILE_SYNC: '文件同步',
  DIRECT: '直接共享',
  PROCESSED: '加工共享',
  CONDITIONAL: '有条件共享',
  NOT_SHARE: '不予共享',
  SOCIAL_OPEN: '可对社会开放',
  NOT_OPEN: '不可对社会开放',
  PARTIAL_OPEN: '部分对社会开放',
  UNCONDITIONAL: '无条件共享',
  RESTRICTED: '受限共享',
  NEED_COLLECT: '需采集',
  AUTHORIZE_EXISTING: '授权现有',
  // 通道类型
  FTP: 'FTP',
  S3: '对象存储(S3)',
  LOCAL: '本地文件',
  NAS: 'NAS存储',
  GZIP: 'GZIP压缩',
  NO_COMPRESSION: '不压缩',
  UNSTRUCT: '非结构化',
  SEMI: '半结构化',
  BASE: '基础库',
  TOPIC: '专题库',
  CDC: 'CDC增量',
  // 作业/管道/策略类型
  PROBE: '探测',
  RECONCILE: '对账',
  CLEAN: '清洗',
  TAG: '标注',
  LINK: '关联',
  CLASSIFY: '分类',
  BACKUP: '备份',
  DESTROY: '销毁',
  // 异议类型
  QUALITY: '质量',
  COMPLETENESS: '完整性',
  VALIDITY: '有效性',
  CONSISTENCY: '一致性',
  AUTH: '授权',
  // 严重级别
  HIGH: '高',
  HIGHEST: '最高',
  MEDIUM: '中',
  LOW: '低',
  RUNNING_EXECUTION: '执行中',
  SUBMITTED_SUCCESS: '已提交',
  DELAY_EXECUTION: '延时执行',
  SERIAL_WAIT: '串行等待',
  READY_PAUSE: '准备暂停',
  PAUSE: '已暂停',
  READY_STOP: '准备停止',
  FORCED_SUCCESS: '强制成功',
  WAITING_THREAD: '等待线程',
  WAITING_DEPEND: '等待依赖',
  WAITING_DEPENDENCY: '等待依赖',
  ACCEPT: '已受理',
  EMAIL: '邮件',
  SMS: '短信',
  DELETE: '删除',
  DATABASE: '数据库',
  OTHER: '其他',
  REALTIME: '实时',
  HOURLY: '每小时',
  DAILY: '每日',
  WEEKLY: '每周',
  MONTHLY: '每月',
  YEARLY: '每年',
  // 质量检查 / 问题类型
  NULL_CHECK: '空值检查',
  UNIQUENESS: '唯一性',
  RECORD_COUNT: '记录数',
  ACCURACY: '准确性',
  INTEGRITY: '完整性',
  AVAILABILITY: '可用性',
  SECURITY: '安全性',
  PERFORMANCE: '性能',
  DB: '数据库',
  STORAGE: '存储',
  CHANNEL: '传输通道',
  BACKUP: '备份',
  CATALOG: '资产目录',
  AUDIT: '访问审计',
  PERF: '性能',
  CATALOG_EXCHANGE: '目录交换通道',
  BACKUP_TRANSFER: '备份传输通道',
  LOCAL_FALLBACK: '本地降级',
  IDLE: '空闲',
  NULL: '空值',
  NULL_VALUE: '空值',
  DUPLICATE: '重复值',
  INVALID: '无效值',
  COUNT: '计数异常',
  OUT_OF_RANGE: '超范围',
  FORMAT_ERROR: '格式错误',
  THRESHOLD: '超阈值',
  // 质量问题分析
  IN_ANALYSIS: '分析中',
  LOCATE: '快速定位',
  CODE_MAP: '编码映射',
  PROCESS: '流程整改',
  CODE_MISMATCH: '编码不匹配',
  PARTIAL_MAP: '部分对标',
  // 脚本/组件类型
  SELECT: '查询',
  FORM: '表单',
  LIST: '列表',
  UNIT: '单元',
  COMPOSITE: '复合',
  // 供需清单
  SUPPLY: '供给',
  DEMAND: '需求',
  // 常见数据源类型（展示名可与品牌一致）
  MYSQL: 'MySQL',
  POSTGRESQL: 'PostgreSQL',
  POSTGRES: 'PostgreSQL',
  ORACLE: 'Oracle',
  SQLSERVER: 'SQL Server',
  HIVE: 'Hive',
  CLICKHOUSE: 'ClickHouse',
  MONGODB: 'MongoDB',
  REDIS: 'Redis',
  CSV: 'CSV',
  EXCEL: 'Excel',
  JSON: 'JSON',
  FILE: '文件',
  KAFKA: 'Kafka',
  ELASTICSEARCH: 'Elasticsearch',
  // 需求/任务类型
  STRUCTURED: '结构化',
  UNSTRUCTURED: '非结构化',
  COLLECT: '归集',
  SHARE: '共享',
  EXCHANGE: '交换',
  // 评价周期 / 指标 / 对象
  WEEK: '周',
  MONTH: '月',
  QUARTER: '季',
  QUARTERLY: '每季',
  HALF_YEAR: '半年',
  YEAR: '年',
  A: 'A自动',
  B: 'B人工',
  REGION: '区域',
  DEPT: '部门',
  POSITION: '岗位',
  SYSTEM: '业务系统',
  // 质量规则
  CONSISTENCY: '一致性',
  TIMELINESS: '及时性',
  // 指标/字段值类型（非 DB dataType 列）
  STRING: '字符串',
  NUMBER: '数字',
  DATE: '日期',
  BOOLEAN: '布尔',
  // 媒介 / 应用
  DOCUMENT: '文档',
  IMAGE: '图片',
  AV: '音视频',
  VIDEO: '视频',
  AUDIO: '音频',
  WEB: 'Web',
  // 分区类型
  RANGE: '范围',
  HASH: '哈希',
  // 分区运维
  MIGRATE: '分区迁移',
  COMPRESS: '数据压缩',
  REBUILD_INDEX: '重建索引',
  CLEANUP: '数据清理',
  RESTORE_PLAN: '恢复计划',
  UNEVEN: '分布不均',
  // 血缘边 / 探查实体
  FLOW: '数据流',
  EXTRACT: '抽取',
  CROSS_DB: '跨库',
  ENTERPRISE: '企业',
  PERSON: '人员',
  // 授权对象补充（ORG/USER/ROLE/TABLE/COLUMN 已有）
  AUTHORIZE: '授权',
  // 分级分类
  GENERAL: '一般数据',
  IMPORTANT: '重要数据',
  CORE: '核心数据',
  MANUAL: '人工',
  RULE_SUGGEST: '规则建议',
  SUGGESTED: '建议待确认',
  SUGGEST: '建议打标',
  AUTO: '自动打标',
  KEEP_MANUAL: '不覆盖人工',
  PRIORITY: '优先级最高',
  OVERRIDE: '覆盖已有',
  RULE: '规则',
  IMPORT: '导入',
  BUSINESS: '业务域',
  THEME: '主题',
  OBJECT: '数据对象',
  SCENE: '应用场景',
  FREQUENCY: '更新频率',
  QUALITY: '质量等级',
  OTHER: '其他',
  ENUM: '枚举',
  TREE: '层级树',
  TEXT: '自由文本',
  BOOL: '布尔',
  MULTI: '多值',
  STANDARD: '国标',
  CUSTOM: '自定义',
  CREATE_TAG: '创建标签',
  UPDATE_TAG: '更新标签',
  BIND: '打标',
  UNBIND: '摘标',
  REJECT: '驳回',
  RULE_RUN: '规则执行',
  MERGE: '合并标签',
  // 数据搜索
  FUZZY: '智能模糊',
  EXACT: '精确标识',
  META: '元数据找表',
  COMBO: '多维组合',
  NEAR_REALTIME: '近实时',
  SCHEDULED: '定时批量',
  FULL_REBUILD: '全量重建',
  SYNONYM: '同义词',
  DICT: '词典',
  IDENTITY_RULE: '标识规则',
  FIELD_ALIAS: '字段别名',
  WEIGHT: '权重',
  UI_CONFIG: '交互配置',
  CLASS_TAG_MAP: '分类标签映射',
  ID_CARD: '身份证',
  CREDIT_CODE: '统一社会信用代码',
  PHONE: '手机号',
  SEARCH: '检索',
  CLICK: '点击',
  BROWSE: '浏览',
  DOWNLOAD: '下载',
  EXACT_PROFILE: '精确画像',
  SECONDARY: '二次检索',
  SYNC: '同步',
  CONFIG: '配置',
  GLOBAL_BIND: '全局绑定',
  IDENTITY: '标识融合',
  LIVE: '实时查询',
  EXCLUDED: '已排除',
  RELEVANCE: '相关度',
  PROJECT: '项目血缘',
  AGGREGATE: '聚合示意',
  BIZ_ASSET: '业务资产',
  EXTRACT: '抽取',
  PUBLISH: '发布',
  REVIEWED: '审核确认',
  BATCH: '批量',
  ALLOW: '允许',
  DENY: '拒绝',
  SHARE: '共享',
  EXPORT: '导出',
  TRANSFER: '流转',
  VIEW: '访问',
  ASSET: '数据资产',
  REGISTRY: '编目',
  // 脱敏
  MASK: '掩码',
  REPLACE: '替换',
  TRUNCATE: '截断',
  GENERALIZE: '泛化',
  HASH: '哈希',
  CLEAR: '置空',
  CONSTANT: '常数',
  ENCRYPT: '加密',
  FPE: '格式保留加密',
  PREVIEW: '预览',
  APPLY: '执行',
  PUBLISH: '发布',
  RESTORE: '还原',
  CONFIG: '配置',
  QUERY: '在线查询',
  LIST: '列表',
  DETAIL: '详情',
  API_SHARE: '接口',
  OPEN_DOWNLOAD: '开放下载',
  TEST_SYNC: '测试同步',
  LOG: '日志',
}

/**
 * 数据资源目录生命周期状态（列表「状态」列）。
 * 以 approvalStatus 为主；下线后后端会回到 DRAFT，不再单独展示发布态。
 * 返回码：DRAFT / TO_REGISTER / PENDING / APPROVED / REJECTED
 */
export function catalogResourceStatusCode(approvalStatus?: string | null, publishStatus?: string | null): string {
  const a = String(approvalStatus ?? 'DRAFT').trim().toUpperCase()
  const p = String(publishStatus ?? '').trim().toUpperCase()
  if (a === 'PENDING') return 'PENDING'
  if (a === 'TO_REGISTER') return 'TO_REGISTER'
  if (a === 'REJECTED') return 'REJECTED'
  if (a === 'APPROVED') return 'APPROVED'
  // 下线后回编目可再编辑，展示「已下线」
  if (p === 'OFFLINE') return 'OFFLINE'
  // WITHDRAWN 等历史态按草稿展示（可再编辑提交）
  return 'DRAFT'
}

export function catalogResourceStatusLabel(approvalStatus?: string | null, publishStatus?: string | null): string {
  return statusLabel(catalogResourceStatusCode(approvalStatus, publishStatus))
}

/** `NONE` 在不同字段含义不同，须按 domain 消歧，避免压缩/加密码覆盖执行状态。 */
export type StatusLabelDomain = 'exec' | 'calc' | 'compress' | 'encrypt'

const NONE_LABEL_BY_DOMAIN: Record<StatusLabelDomain, string> = {
  exec: '未执行',
  calc: '未生成',
  compress: '不压缩',
  encrypt: '不加密',
}

/**
 * 将后端状态码转为中文；未知码原样返回（便于发现漏映射）。
 * 数值状态：1→启用 / 0→停用（账号等）。
 * `NONE` 默认按执行状态「未执行」；压缩/加密/计算结果请传 domain。
 */
export function statusLabel(value: unknown, domain?: StatusLabelDomain): string {
  if (value === null || value === undefined || value === '') return '—'
  if (typeof value === 'number') {
    if (value === 1) return '启用'
    if (value === 0) return '停用'
    return String(value)
  }
  const key = String(value).trim().toUpperCase()
  if (key === 'NONE' && domain) {
    return NONE_LABEL_BY_DOMAIN[domain]
  }
  return STATUS_ZH[key] || String(value)
}

export function statusTagType(value: unknown): 'success' | 'warning' | 'info' | 'danger' | 'primary' {
  const key = String(value ?? '').trim().toUpperCase()
  if (['ACTIVE', 'ENABLED', 'SUCCESS', 'APPROVED', 'COMPLETED', 'FINISHED', 'CONFIRMED', 'CATALOG_MOUNTED', 'PUBLISHED', 'READY', 'CONFIGURED', 'NORMAL', 'SUBSCRIBED', 'DISTRIBUTED', 'MAPPED', 'MATCHED', 'INDEXED', 'OK', 'IMPLEMENTED', 'ONLINE', 'UP', 'PASS', 'UNDERSTOOD', 'POSITIVE', 'CLEANED', 'CLEANED_IN', 'PUBLIC', 'ACKED', 'READ'].includes(key)) {
    return 'success'
  }
  if (['PENDING', 'PENDING_ARCHIVE', 'PENDING_REVIEW', 'RUNNING', 'ANALYZING', 'PRE_AUDITING', 'CORRECTION', 'WAITING', 'DRAFT', 'TO_REGISTER', 'SUPERVISING', 'DISPATCHED', 'PROVIDER_RETURNED', 'FULFILLING', 'PARTIAL', 'WARN', 'POC', 'MEDIUM', 'RAW', 'EXTRACTED', 'TAGGED', 'LEDGER', 'OPEN', 'OTHER', 'PRIVATE', 'UNEVEN', 'WITHDRAW_PENDING', 'IN_ANALYSIS', 'PARTIAL_MAP', 'UNREAD'].includes(key)) {
    return 'warning'
  }
  if (['REJECTED', 'FAILED', 'ERROR', 'FATAL', 'CANCELLED', 'ABNORMAL', 'EXPIRED', 'RETURNED', 'STOPPED', 'UNMAPPED', 'UNMATCHED', 'CRITICAL', 'BLOCKED', 'MISSING', 'HIGH', 'DOWN', 'FAIL', 'NEGATIVE', 'PROBLEM', 'ABANDONED', 'REVOKED'].includes(key)) {
    return 'danger'
  }
  if (['INACTIVE', 'DISABLED', 'OFFLINE', 'CLOSED', 'WITHDRAWN', 'ARCHIVED', 'DESTROYED', 'STUB', 'EXTERNAL', 'SKIPPED', 'UNTESTED', 'LOW', 'NONE', 'NOT_RUN', 'NOT_GENERATED'].includes(key)) {
    return 'info'
  }
  return 'info'
}
