param(
  [switch]$Force,
  [string]$MidHost = '10.10.10.51',
  [string]$AppHost = '10.10.10.55'
)
# Generate local prod env files: compose/prod-mid.env + compose/prod-app.env
# Reuse existing files by default; -Force to regenerate secrets
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Compose = Join-Path $Root "compose"
$midPath = Join-Path $Compose "prod-mid.env"
$appPath = Join-Path $Compose "prod-app.env"
$sheetPath = Join-Path $Compose "prod-secrets.local.txt"

function New-Secret([int]$Length = 28) {
  # 避免 # 与空白：Compose env 中 # 会开启注释导致密码被截断为空
  $chars = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@%^*_+-="
  $bytes = New-Object byte[] $Length
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
  return (-join ($bytes | ForEach-Object { $chars[$_ % $chars.Length] }))
}

function Quote-EnvValue([string]$Value) {
  # 含特殊字符时加双引号，内部双引号转义
  if ($Value -match '[#\s"''`$\\=!]') {
    return '"' + ($Value -replace '\\', '\\' -replace '"', '\"') + '"'
  }
  return $Value
}

function Write-Utf8NoBom([string]$Path, [string]$Content) {
  $utf8 = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

# 生产 env 必须用 Unix LF：Windows CRLF 会让 Linux 上 grep/cut 读出带 \r 的端口（mysqldump 失败）
function ConvertTo-UnixLfFile([string]$Path) {
  if (-not (Test-Path $Path)) { return }
  $text = [System.IO.File]::ReadAllText($Path) -replace "`r`n", "`n" -replace "`r", "`n"
  if (-not $text.EndsWith("`n")) { $text = $text + "`n" }
  Write-Utf8NoBom $Path $text
}

if (-not $Force -and (Test-Path $midPath) -and (Test-Path $appPath)) {
  ConvertTo-UnixLfFile $midPath
  ConvertTo-UnixLfFile $appPath
  if (Test-Path $sheetPath) { ConvertTo-UnixLfFile $sheetPath }
  Write-Host "==> already have compose/prod-mid.env + prod-app.env (normalized to LF; use -Force to regenerate)"
  exit 0
}

$mysqlRoot = New-Secret 32
$mysqlUser = New-Secret 28
$redis = New-Secret 28
$kettle = New-Secret 24
$jwt = New-Secret 48
$cred = New-Secret 36
$ossMysql = New-Secret 24

# 强制 LF，勿用 [Environment]::NewLine（Windows 上是 CRLF）
$nl = "`n"
$midLines = @(
  "# mid host $MidHost - generated by scripts/gen_prod_env.ps1 (do not commit)",
  "MYSQL_ROOT_PASSWORD=$(Quote-EnvValue $mysqlRoot)",
  "MYSQL_DATABASE=smart_city",
  "MYSQL_USER=smart_city",
  "MYSQL_PASSWORD=$(Quote-EnvValue $mysqlUser)",
  "MYSQL_PUBLISH_PORT=13306",
  "",
  "REDIS_PASSWORD=$(Quote-EnvValue $redis)",
  "REDIS_PUBLISH_PORT=6379",
  "",
  "OSS_MYSQL_ROOT_PASSWORD=$(Quote-EnvValue $ossMysql)",
  "KETTLE_USER=cluster",
  "KETTLE_PASSWORD=$(Quote-EnvValue $kettle)",
  "KETTLE_PUBLISH_PORT=18081",
  "",
  'ES_JAVA_OPTS="-Xms1g -Xmx1g"'
)
$appLines = @(
  "# app host $AppHost - generated by scripts/gen_prod_env.ps1 (do not commit)",
  "WEB_PUBLISH_PORT=80",
  "BACKEND_PUBLISH_PORT=8080",
  "DE_EMBED_BASE=http://${AppHost}",
  "",
  "MYSQL_HOST=$MidHost",
  "MYSQL_PORT=13306",
  "MYSQL_DATABASE=smart_city",
  "MYSQL_USER=smart_city",
  "MYSQL_PASSWORD=$(Quote-EnvValue $mysqlUser)",
  "",
  "REDIS_HOST=$MidHost",
  "REDIS_PORT=6379",
  "REDIS_PASSWORD=$(Quote-EnvValue $redis)",
  "",
  "APP_JWT_SECRET=$(Quote-EnvValue $jwt)",
  "CREDENTIAL_KEY=$(Quote-EnvValue $cred)",
  "INTEGRATION_ENABLED=true",
  "",
  "OM_URL=http://${MidHost}:8585/api/v1",
  "OM_USER=admin@openmetadata.org",
  "OM_PASSWORD=admin",
  "DE_URL=http://${MidHost}:8100",
  "DS_URL=http://${MidHost}:12345/dolphinscheduler",
  "DS_USER=admin",
  "DS_PASSWORD=dolphinscheduler123",
  "KETTLE_URL=http://${MidHost}:18081",
  "KETTLE_USER=cluster",
  "KETTLE_PASSWORD=$(Quote-EnvValue $kettle)",
  "KETTLE_TARGET_HOST=$MidHost",
  "KETTLE_TARGET_PORT=13306",
  "KETTLE_TARGET_DB=smart_city_ods",
  "KETTLE_CARTE_HOST=$MidHost",
  "KETTLE_CARTE_PORT=18081",
  "ES_URL=http://${MidHost}:9200",
  "SEAWEED_S3_ENDPOINT=http://${MidHost}:8333",
  "SEAWEED_S3_BUCKET=smartcity-docs",
  "MONGO_URL=mongodb://${MidHost}:27017",
  "CANAL_URL=http://${MidHost}:19090",
  "",
  'BACKEND_JAVA_OPTS="-Xms1g -Xmx3g"'
)
$sheetLines = @(
  "chengde prod secrets (local only, do not commit)",
  "generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
  "mid=$MidHost app=$AppHost",
  "",
  "MYSQL_ROOT_PASSWORD=$mysqlRoot",
  "MYSQL_USER=smart_city",
  "MYSQL_PASSWORD=$mysqlUser",
  "REDIS_PASSWORD=$redis",
  "KETTLE_PASSWORD=$kettle",
  "OSS_MYSQL_ROOT_PASSWORD=$ossMysql",
  "APP_JWT_SECRET=$jwt",
  "CREDENTIAL_KEY=$cred",
  "",
  "OM_PASSWORD=admin",
  "DS_PASSWORD=dolphinscheduler123"
)

Write-Utf8NoBom $midPath (($midLines -join $nl) + $nl)
Write-Utf8NoBom $appPath (($appLines -join $nl) + $nl)
Write-Utf8NoBom $sheetPath (($sheetLines -join $nl) + $nl)

Write-Host "==> wrote $midPath"
Write-Host "==> wrote $appPath"
Write-Host "==> wrote $sheetPath"
exit 0
